### ISSUE TITLE
PUCLIB.dll was not found

### ISSUE THREAD

**Issue by TG-san** [infinicam/CamMonitor#4]
Hi, I faced an error that "The code execution cannot process because PUCLIB.dll was not found. Reinstalling the program may fix this problem". Would you please let me know if you have any ideas to solve this problem. Thanks,

**Comment by PhotronSupport** [comment]
Hi, TG-san.
I'm Kojima, in charge of technical support for Photron.
I apologize for the delay in replying to your question.

As for the error about PUCLIB.dll not being found, how about moving the two DLLs to the folder where the exe file is located?
Their DLLs must be in the folder specified by the IDE such as Visual Studio, in the system folder, or in the same folder as the exe.

It's in Japanese, but I've attached screenshots.

![INFINICAM](https://user-images.githubusercontent.com/75958981/104551537-68d94380-567a-11eb-8f67-114511d78aed.jpg)
![INFINICAM2](https://user-images.githubusercontent.com/75958981/104551549-6d056100-567a-11eb-80c1-80bc4aec2391.jpg)

I pray that this problem will be solved.
